name: Coverage for pull request
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Run Coverage
        run: |
          chmod +x gradlew
          ./gradlew test
      - name: Archive test results
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          retention-days: 5
          path: |
            build/reports/tests/test/*
      - name: Archive jacoco results
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report
          retention-days: 5
          path: |
            build/reports/jacoco/test/html/*
      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.2
        with:
          paths: ${{ github.workspace }}/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 0
          min-coverage-changed-files: 0
